spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookshelf?serverTimezone=Asia/Seoul
    username: team
    password: 1234

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

  data:
    web:
      pageable:
        default-page-size: 10

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:templates/
  suffix: .html
  enabled: true

server:
  servlet:
    session:
      tracking-modes: cookie

social:
  client:
    kakao:
      rest-api-key: 71f9ffc4fdde0af1bb644b5621d1f045
      secret-key: iM9KTaRdZp88PbaXY6PSUnFqCulL3T1K
      grant_type: authorization_code
      redirect-uri: http://localhost:8080/login/api/kakao
      admin-key: 4e20c2bfb12465ca5e81c238388ddaf8
      logout-redirect-uri: http://localhost:8080/logout/api/kakao


    naver:
      rest-api-key: r5UySheAPrPbFPYnqJCq
      secret-key: Nbg6wfyk4J
      redirect-uri: http://localhost:8080/api/login/naver
      grant_type: authorization_code

    google:
      rest-api-key: 216152233037-ll5ocvvp8d3mn367k7s0kmsb1r09v02d.apps.googleusercontent.com
      secret-key: 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
      redirect-uri: http://localhost:8080/login/api/google
      grant_type: authorization_code

    message:
      api-key: NCSOTHPPYKFF0STE
      secret-key: W9D6CUGQAPNXNDN4CMBF9SCEXIFZN1EZ

